name = "TestAKS"
uuid = "1a6b80b5-ae4a-434a-a350-9eef1154c046"
authors = ["Alok Sahoo"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
